name: my_camera_project
description: A new Flutter project using the camera.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.17.1
  firebase_analytics: 10.10.7
  firebase_auth: ^4.20.0
  google_sign_in: ^6.2.1
  cloud_firestore: ^4.17.5
  camera: ^0.10.0+3
  path_provider: ^2.0.11
  firebase_storage: ^11.0.7
  table_calendar: ^3.0.9
  carousel_slider: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
